services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    networks:
      - app-network

  backend1:
    build: ./backend
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
    depends_on:
      - database
      - cache
    networks:
      - app-network

  backend2:
    build: ./backend
    environment:
      - PORT=4002
    ports:
      - "4002:4002"
    depends_on:
      - database
      - cache
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
    networks:
      - app-network


  database:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  cache:
    image: redis:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
